use_frameworks!

platform :ios, '9.0'

target 'SecondCocoapodsLib_Example' do
  pod 'SecondCocoapodsLib', :path => '../'

  target 'SecondCocoapodsLib_Tests' do
    inherit! :search_paths

    
  end
end
